# Generated by Django 6.0.5 on 2026-05-22 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., SMVITM - Udupi", max_length=255),
                ),
                ("duration_days", models.IntegerField(help_text="Duration in days")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "technology",
                    models.CharField(
                        help_text="e.g., Django, Python Fullstack", max_length=255
                    ),
                ),
                (
                    "semester_year",
                    models.CharField(
                        help_text="e.g., 4th Sem, 6th Sem", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Completed", "Completed")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyWorkload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "sessions_count",
                    models.IntegerField(
                        choices=[(2, "2 Sessions per Day"), (3, "3 Sessions per Day")],
                        default=2,
                    ),
                ),
                (
                    "topics_covered",
                    models.TextField(help_text="Topics covered in the sessions"),
                ),
                (
                    "subtopics_covered",
                    models.TextField(help_text="Subtopics covered in the sessions"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_workloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_workloads",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("trainer", "project", "date")},
            },
        ),
        migrations.CreateModel(
            name="ClassWorkNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="workloads/notes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="core.dailyworkload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(help_text="e.g., YYYY-MM format", max_length=7),
                ),
                ("total_working_days", models.IntegerField(default=0)),
                ("total_holidays", models.IntegerField(default=0)),
                (
                    "sick_leaves",
                    models.IntegerField(
                        default=0, help_text="Sick or other medical leaves (deductible)"
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending Review"),
                            ("Approved", "Approved"),
                            ("Paid", "Paid"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Travel", "Travel/Transport"),
                            ("Accommodation", "Accommodation/Hotel"),
                            ("Food", "Food/Meals"),
                            ("Trainer Fee", "Trainer Fee/Honorarium"),
                            ("Materials", "Training Materials/Infrastructure"),
                            ("Miscellaneous", "Miscellaneous Expenses"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TrainerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="trainers/photos/"
                    ),
                ),
                (
                    "aadhaar_number",
                    models.CharField(
                        help_text="12-digit Aadhaar Number", max_length=12
                    ),
                ),
                (
                    "aadhaar_file",
                    models.FileField(
                        blank=True, null=True, upload_to="trainers/aadhaar/"
                    ),
                ),
                (
                    "pan_card",
                    models.CharField(
                        help_text="10-digit PAN Card Number", max_length=10
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_account_number", models.CharField(max_length=50)),
                ("bank_ifsc", models.CharField(help_text="IFSC Code", max_length=20)),
                (
                    "upi_id",
                    models.CharField(
                        help_text="UPI ID (e.g. user@okaxis)", max_length=100
                    ),
                ),
                (
                    "quoted_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in INR", max_digits=10
                    ),
                ),
                (
                    "quoted_type",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily Rate (INR)"),
                            ("Monthly", "Monthly Rate (INR)"),
                        ],
                        default="Daily",
                        max_length=10,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, help_text="Approved by admin"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active status"),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, related_name="trainers", to="core.project"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
