# Generated by Django 6.0.5 on 2026-05-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyworkload",
            name="subtopics_covered",
            field=models.TextField(
                blank=True, help_text="Summary of subtopics covered", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dailyworkload",
            name="topics_covered",
            field=models.TextField(
                blank=True, help_text="Summary of topics covered", null=True
            ),
        ),
        migrations.CreateModel(
            name="SessionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_num", models.IntegerField()),
                (
                    "time_slot",
                    models.CharField(
                        help_text="e.g. 09:00 AM - 11:00 AM", max_length=100
                    ),
                ),
                ("batch", models.CharField(help_text="e.g. Batch A", max_length=100)),
                ("content_covered", models.TextField()),
                (
                    "workload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_details",
                        to="core.dailyworkload",
                    ),
                ),
            ],
            options={
                "ordering": ["session_num"],
                "unique_together": {("workload", "session_num")},
            },
        ),
    ]
